# Generated by Django 3.2.9 on 2022-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=75)),
                ('lname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
                ('website', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=255)),
                ('confirm', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
